### ISSUE TITLE
[Frontend] - Profile for frontend

### ISSUE THREAD

**Issue by NumNine9** [Gazzo-gif/Desk-Sharing-Tool#10]
Put this settings in the sidebar instead of a separate page

- [x] Change visibility
- [x] Change password
- [x] Know who has logged in (show name)

**Comment by Burakalpyel** [comment]
Sidebar

**Comment by DaGeRe** [comment]
Sichtweite -> Sichtbarkeit
Kennwort -> Passwort
Password twice
